name: Unit Test Suite
on: push

jobs:
    unit-tests:
        name: PHPUnit test suite
        runs-on: ubuntu-latest
        services:
            # MySQL source DB
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: fregata_source
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
            # PostgreSQL destination DB
            postgres:
                image: postgres:11
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: fregata_target
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

        steps:
            # Setup
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: PHP setup
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'
                    extensions: json pdo_mysql pdo_pgsql

            # Cache Composer dependencies
            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Install dependencies
                run: composer install --prefer-dist

            # Run tests suite
            -   name: Run test suite
                run: php vendor/bin/phpunit
